name: CI/CD Pipeline (GitOps)

on:
  push:
    branches: [main] # source of truth main branch declaring state of all infra and app state
  
jobs:
  build:
    runs-on: ubuntu-latest # job will run on fresh ubuntu VM
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Pulls the repository code into the runner
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build, tag, push image to Dockerhub
        env: 
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          IMAGE_NAME: tinker
        run: | 
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest 
  test:
    runs-on: ubuntu-latest # job will run on fresh ubuntu VM
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Pulls the repository code into the runner
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Test with pytest
        run: | 
          pip install pytest
          pytest test.py
      #- name: Lint
      #  uses: flakes8 
